const localPoemsData = [
    { "id": 1, "title": "Anlatamıyorum", "authorName": "Orhan Veli Kanık", "text": "Ağlasam sesimi duyar mısınız,\nMısralarımda;\nDokunabilir misiniz,\nGözyaşlarıma, ellerinizle?\n\nBilmezdim şarkıların bu kadar güzel,\nKelimelerinse kifayetsiz olduğunu\nBu derde düşmeden önce.\n\nBir yer var, biliyorum;\nHer şeyi söylemek mümkün;\nEpeyce yaklaşmışım, duyuyorum;\nAnlatamıyorum." },
    { "id": 2, "title": "Seviyorum Seni", "authorName": "Nazım Hikmet Ran", "text": "Seviyorum seni\nekmeği tuza banıp yer gibi\nGeceleyin ateşler içinde uyanarak\nağzımı dayayıp musluğa su içer gibi\nAğır posta paketini, neyin nesi belirsiz,\ntelaşlı, sevinçli, kuşkulu açar gibi\nSeviyorum seni\ndenizi ilk defa uçakla geçer gibi\nİstanbul'da yumuşacık kararırken ortalık\niçimde kımıldayan bir şeyler gibi\nSeviyorum seni\nYaşıyoruz çok şükür der gibi." },
    { "id": 3, "title": "Ben Sana Mecburum", "authorName": "Attilâ İlhan", "text": "Ben sana mecburum bilemezsin\nAdını mıh gibi aklımda tutuyorum\nBüyüdükçe büyüyor gözlerin\nBen sana mecburum bilemezsin\nİçimi seninle ısıtıyorum.\n\nAğaçlar sonbahara hazırlanıyor\nBu şehir o eski İstanbul mudur\nKaranlıkta bulutlar parçalanıyor\nSokak lambaları birden yanıyor\nKaldırımlarda yağmur kokusu\nBen sana mecburum sen yoksun." },
    { "id": 4, "title": "Üvercinka", "authorName": "Cemal Süreya", "text": "Böylece bir kere daha boynunlayız sayılı yerlerinden\nEn uzun boynun bu senin dayanmaya ya da umudu kesmemeye\nLaleli'den dünyaya doğru giden bir tramvaydayız\nBirden nasıl oluyor sen yüreğimi elliyorsun\nAma nasıl oluyor sen yüreğimi eller ellemez\nSevişmek bir kere daha yürürlüğe giriyor\nBütün kara parçalarında\nAfrika dahil." },
    { "id": 5, "title": "Otuz Beş Yaş", "authorName": "Cahit Sıtkı Tarancı", "text": "Yaş otuz beş! yolun yarısı eder.\nDante gibi ortasındayız ömrün.\nDelikanlı çağımızdaki cevher,\nYalvarmak, yakarmak nafile bugün,\nGözünün yaşına bakmadan gider.\n\nŞakaklarıma kar mı yağdı ne var?\nBenim mi Allahım bu çizgili yüz?\nYa gözler altındaki mor halkalar?\nNeden böyle düşman görünürsünüz,\nYıllar yılı dost bildiğim aynalar?" },
    { "id": 6, "title": "Kaldırımlar", "authorName": "Necip Fazıl Kısakürek", "text": "Sokaktayım, kimsesiz bir sokak ortasında;\nYürüyorum, arkama bakmadan yürüyorum.\nYolumun karanlığa saplanan noktasında,\nSanki beni bekleyen bir hayal görüyorum.\n\nKara gökler kül rengi bulutlarla kapanık;\nEvlerin bacasını kolluyor yıldırımlar.\nİn cin uykuda, yalnız iki yoldaş uyanık;\nBiri benim, biri de serseri kaldırımlar." },
    { "id": 7, "title": "Sessiz Gemi", "authorName": "Yahya Kemal Beyatlı", "text": "Artık demir almak günü gelmişse zamandan\nMeçhule giden bir gemi kalkar bu limandan.\n\nHiç yolcusu yokmuş gibi sessizce alır yol;\nSallanmaz o kalkışta ne mendil, ne de bir kol.\n\nRıhtımda kalanlar bu seyahatten elemli,\nGünlerce siyah ufka bakar gözleri nemli,\n\nBiçare gönüller! Ne giden son tekne midir bu!\nHicranlı hayatın ne de son matemidir bu." },
    { "id": 10, "title": "Göğe Bakma Durağı", "authorName": "Turgut Uyar", "text": "İkimiz birden sevinebiliriz göğe bakalım\nŞu kaçamak ışıklardan şu şeker kamışlarından\nBebe dişlerinden güneşlerden yaban otlarından\nDurmadan harcadığım şu gözlerimi al kurtar\nŞu aranıp duran korkak ellerimi tut\nBu evleri atla bu evleri de bunları da\nGöğe bakalım\n\nFalanca durağa şimdi geliriz göğe bakalım\nİnecek var deriz otobüs durur ineriz\nBu karanlık böyle iyi afferin Tanrıya\nHerkes uyusun iyi oluyor hoşlanıyorum\nHırsızlar polisler açlar toklar uyusun\nHerkes uyusun bir seni uyutmam bir de ben uyumam\nHerkes yokken biz oluruz biz uyumayalım\nNasıl olsa sarhoşuz nasıl olsa öpüşürüz sokaklarda\nBeni bırak göğe bakalım" },
    { "id": 11, "title": "Lavinia", "authorName": "Özdemir Asaf", "text": "Sana gitme demeyeceğim.\nÜşüyorsun ceketimi al.\nGünün en güzel saatleri bunlar.\nYanımda kal.\n\nSana gitme demeyeceğim.\nGene de sen bilirsin.\nYalanlar istiyorsan yalanlar söyleyeyim,\nİncinirsin.\n\nSana gitme demeyeceğim,\nAma gitme, Lavinia.\nAdını gizleyeceğim\nSen de bilme, Lavinia." },
    { "id": 12, "title": "Masa da Masaymış Ha", "authorName": "Edip Cansever", "text": "Adam yaşama sevinci içinde\nMasaya anahtarlarını koydu\nBakır kâseye çiçekleri koydu\nSütünü yumurtasını koydu\nPencereden gelen ışığı koydu\nBisiklet sesini çıkrık sesini\nEkmeğin havanın yumuşaklığını koydu\nAdam masaya\nAklında olup bitenleri koydu\nNe yapmak istiyordu hayatta\nİşte onu koydu\n\nKimi seviyordu kimi sevmiyordu\nAdam masaya onları da koydu\nÜç kere üç dokuz ederdi\nAdam koydu masaya dokuzu\nPencere yanındaydı gökyüzü yanında\nUzandı masaya sonsuzu koydu\nBir bira içmek istiyordu kaç gündür\nMasaya biranın dökülüşünü koydu\nUykusunu koydu uyanıklığını koydu\nTokluğunu açlığını koydu.\n\nMasa da masaymış ha\nBana mısın demedi bu kadar yüke\nBir iki sallandı durdu\nAdam ha babam koyuyordu." },
    { "id": 13, "title": "Desem Ki", "authorName": "Cahit Sıtkı Tarancı", "text": "Desem ki vakitlerden bir Nisan akşamıdır,\nRüzgarların en ferahlatıcısı senden esiyor,\nSende seyrediyorum denizlerin en mavisini,\nOrmanların en kuytusunu sende gezmekteyim,\nSenden kopardım çiçeklerin en solmazını,\nToprakların en bereketlisini sende sürdüm,\nSende tattım yemişlerin cümlesini.\n\nDesem ki sen benim için,\nHava kadar lazım,\nEkmek kadar mübarek,\nSu gibi aziz bir şeysin;\nNimettensin, nimettensin!\nDesem ki...\nİnan bana sevgilim inan,\nEvimde şenliksin, bahçemde bahar;\nVe soframda en eski şarap.\nBen sende yaşıyorum,\nSen bende hüküm sürmektesin.\nBırak ben söyleyeyim güzelliğini,\nRüzgarlarla, nehirlerle, kuşlarla beraber." },
    { "id": 14, "title": "Beklenen", "authorName": "Necip Fazıl Kısakürek", "text": "Ne hasta bekler sabahı,\nNe taze ölüyü mezar.\nNe de şeytan, bir günahı,\nSeni beklediğim kadar.\n\nGeçti istemem gelmeni,\nYokluğunda buldum seni;\nBırak vehmimde gölgeni\nGelme, artık neye yarar?" },
    { "id": 15, "title": "Deli Kızın Türküsü", "authorName": "Gülten Akın", "text": "Sana büyük caddelerin uğultusunu getirdim\nSağları ölüleri çınlayan evleri\nSana nar çiçeklerini getirdim\nDeniz kıyılarından rüzgârları\nSana ıssız bir gökyüzü getirdim\n\nKuşları uçup gitmiş, aydınlık\nAl bunu ellerine yüzüne sür\nYüreğine sür, günlerin geçsin\nBenim saçlarımda karlar yağıyor\nBenim gözlerimde nehirler buz tutmuş\nSenin için senin için hep senin için\nAğlıyorum..." },
    { "id": 16, "title": "Yaşamaya Dair", "authorName": "Nazım Hikmet Ran", "text": "Yaşamak şakaya gelmez,\nbüyük bir ciddiyetle yaşayacaksın\nbir sincap gibi mesela,\nyani, yaşamanın dışında ve ötesinde hiçbir şey beklemeden,\nyani bütün işin gücün yaşamak olacak.\n\nYaşamayı ciddiye alacaksın,\nyani o derecede, öylesine ki,\nmesela, kolların bağlı arkadan, sırtın duvarda,\nyahut kocaman gözlüklerin,\nbeyaz gömleğinle bir laboratuvarda\ninsanlar için ölebileceksin,\nhem de yüzünü bile görmediğin insanlar için,\nhem de hiç kimse seni buna zorlamamışken,\nhem de en güzel, en gerçek şeyin\nyaşamak olduğunu bildiğin halde." },
    { "id": 17, "title": "Endülüs'te Raks", "authorName": "Yahya Kemal Beyatlı", "text": "Zil, şal ve gül. Bu bahçede raksın bütün hızı...\nŞevk akşamında Endülüs üç defa kırmızı...\n\nAşkın sihirli şarkısı yüzlerce dildedir.\nİspanya neş'esiyle bu akşam bu zildedir.\n\nYelpaze çevrilir gibi birden dönüşleri,\nİşveyle devriliş, saçılış, örtünüşleri...\n\nHer rengi istemez gözümüz şimdi aldadır;\nİspanya dalga dalga bu akşam bu şaldadır.\n\nAlnında halka halkadır aşüfte kâkülü,\nGöğsünde yosma Gırnata'nın en güzel gülü..." }
];