const localAuthorsData = [
    { "id": 1, "name": "Sabahattin Ali", "category": "turk", "isPoet": false, "years": "1907-1948", "movement": "Toplumcu Gerçekçi", "shortBio": "Toplumcu gerçekçi edebiyatımızın en güçlü kalemlerindendir.", "longBio": "25 Şubat 1907'de Gümülcine'de doğan Sabahattin Ali, eserlerinde Anadolu insanının dertlerini, kasaba yaşamını ve insanın iç dünyasındaki yalnızlığı işlemiştir. Markopaşa dergisindeki mizahi yazılarıyla da tanınır.", "quote": "Dünyada hayatın bir tek manası varsa o da sevmektir.", "image": "images/sabahattin-ali.jpg" },
    { "id": 2, "name": "Fyodor Dostoyevski", "category": "dunya", "isPoet": false, "years": "1821-1881", "movement": "Gerçekçilik", "shortBio": "İnsan psikolojisinin derinliklerine inen, Rus edebiyatının dehası.", "longBio": "1821'de doğan yazar, Çarlık Rusya'sında idama mahkum edilip Sibirya'ya gönderilmesiyle büyük bir ruhsal değişim yaşadı. Suç, ahlak, vicdan azabı ve varoluş üzerine yazdığı romanlar edebiyat dünyasında henüz aşılamamıştır.", "quote": "Her insan, herkesin önünde, her şeyden sorumludur.", "image": "images/fyodor-dostoyevski.jpg" },
    { "id": 3, "name": "Oğuz Atay", "category": "turk", "isPoet": false, "years": "1934-1977", "movement": "Postmodernizm", "shortBio": "Türk edebiyatında postmodernizmin öncüsü, aydın bunalımının ustası.", "longBio": "İTÜ İnşaat Fakültesi mezunu olan Atay, 'Tutunamayanlar' eseriyle Türk romanında yapısal bir devrim yapmıştır. Topluma yabancılaşmayı, aydınların bunalımını kara mizah, iç monolog ve bilinçakışı teknikleriyle harmanlayarak anlatmıştır.", "quote": "Ben iç dünyamıza dönüyorum. Orada hayal kırıklığına yer yok.", "image": "images/oguz-atay.jpg" },
    { "id": 4, "name": "Franz Kafka", "category": "dunya", "isPoet": false, "years": "1883-1924", "movement": "Modernizm", "shortBio": "Bürokrasi ve yabancılaşma temalarının dünya çapındaki sembolü.", "longBio": "Prag'da doğan yazar, insanın modern toplumdaki sıkışmışlığını ve suçluluk duygusunu işlemiştir. 'Kafkaesk' terimini dünya lügatine sokmuştur. Eserlerinin çoğunu yaktırmak istemesine rağmen dostu Max Brod sayesinde günümüze ulaşmıştır.", "quote": "Bir kitap, içimizdeki donmuş denize inen bir balta gibi olmalıdır.", "image": "images/franz-kafka.jpg" },
    { "id": 5, "name": "Nazım Hikmet Ran", "category": "turk", "isPoet": true, "years": "1902-1963", "movement": "Serbest Nazım", "shortBio": "Türk şiirine serbest nazımı getiren evrensel usta.", "longBio": "Hece ölçüsünü bırakarak Rus fütüristlerinden etkilenmiş ve Türk şiirine serbest nazımı getirmiştir. Şiirlerinde memleket sevgisini, hasreti ve aşkı destansı bir dille anlatmıştır.", "quote": "Yaşamak şakaya gelmez, büyük bir ciddiyetle yaşayacaksın.", "image": "images/nazim-hikmet-ran.jpg" },
    { "id": 6, "name": "Cemal Süreya", "category": "turk", "isPoet": true, "years": "1931-1990", "movement": "İkinci Yeni", "shortBio": "İkinci Yeni hareketinin öncüsü, aşk ve ironinin kalemi.", "longBio": "Asıl adı Cemalettin Seber'dir. İkinci Yeni şiirinin en popüler ve belirleyici şairlerindendir. Aşkı, erotizmi ve siyasi eleştiriyi zekice bir ironiyle Türk şiirine kazandırmıştır.", "quote": "Hayat kısa, kuşlar uçuyor.", "image": "images/cemal-sureya.jpg" },
    { "id": 8, "name": "Özdemir Asaf", "category": "turk", "isPoet": true, "years": "1923-1981", "movement": "Bağımsız", "shortBio": "Kısa, vurucu ve felsefi şiirlerin unutulmaz şairi.", "longBio": "Şiirlerinde ikilikler, karşıtlıklar ve kelime oyunlarına bolca yer verir. İnsan ilişkilerini, yalnızlığı ve aşkı genellikle epigram (kısa ve özlü) tarzda felsefi bir derinlikle yazmıştır.", "quote": "Yalnızlık paylaşılmaz, paylaşılsa yalnızlık olmaz.", "image": "images/ozdemir-asaf.jpg" },
    { "id": 9, "name": "Ahmet Hamdi Tanpınar", "category": "turk", "isPoet": true, "years": "1901-1962", "movement": "Saf Şiir", "shortBio": "Zaman, rüya ve Doğu-Batı sentezinin en büyük mimarı.", "longBio": "Yahya Kemal'in öğrencisi olan Tanpınar; şiir, roman ve deneme türlerinde eserler vermiştir. Türk insanının Doğu-Batı arasındaki medeniyet krizini psikolojik bir boyutta ele almıştır.", "quote": "Ne içindeyim zamanın, ne de büsbütün dışında.", "image": "images/ahmet-hamdi-tanpinar.jpg" },
    { "id": 10, "name": "Virginia Woolf", "category": "dunya", "isPoet": false, "years": "1882-1941", "movement": "Modernizm", "shortBio": "Bilinçakışı tekniğinin ve feminist edebiyatın İngiliz kraliçesi.", "longBio": "Victoria dönemi kısıtlamalarına karşı çıkarak modernizmi şekillendiren yazar. Karakterlerin iç seslerini aralıksız bir şekilde aktararak edebiyatta zaman algısını değiştirmiştir.", "quote": "Para kazanın, kendinize ait ayrı bir oda yaratın. Ve yazın.", "image": "images/virginia-woolf.jpg" },
    { "id": 11, "name": "Gabriel García Márquez", "category": "dunya", "isPoet": false, "years": "1927-2014", "movement": "Büyülü Gerçekçilik", "shortBio": "Büyülü gerçekçilik akımının Latin Amerikalı Nobel ödüllü dehası.", "longBio": "Latin Amerika'nın mitlerini, acılarını ve tarihini efsanevi bir dille edebiyata kazandırdı. Gerçeküstü olayları son derece sıradanmış gibi anlatma ustasıdır.", "quote": "Hayat, insanın yaşadığı değil; hatırladığıdır.", "image": "images/gabriel-garcia-marquez.jpg" },
    { "id": 12, "name": "Orhan Veli Kanık", "category": "turk", "isPoet": true, "years": "1914-1950", "movement": "Garip Akımı", "shortBio": "Garip akımının kurucusu, sokağın ve sıradan insanın şairi.", "longBio": "Şiiri ölçü, uyak ve şairanelikten kurtararak sokağın dilini edebiyata taşımıştır. Türk şiirindeki en büyük kırılmayı yaratan 'Garip' önsözünü yazmıştır.", "quote": "Beni bu güzel havalar mahvetti.", "image": "images/orhan-veli-kanik.jpg" },
    { "id": 13, "name": "George Orwell", "category": "dunya", "isPoet": false, "years": "1903-1950", "movement": "Distopya", "shortBio": "Distopik edebiyatın ve politik hicvin en büyük ustası.", "longBio": "Totalitarizme, baskıcı rejimlere karşı yazdığı eserlerle 20. yüzyıl siyasi düşüncesini derinden etkilemiş İngiliz yazardır.", "quote": "Gerçeği söylemek devrimci bir eylemdir.", "image": "images/george-orwell.jpg" },
    { "id": 14, "name": "Sait Faik Abasıyanık", "category": "turk", "isPoet": false, "years": "1906-1954", "movement": "Bireyci Öykü", "shortBio": "Türk öykücülüğünün kilometre taşı, İstanbul'un ve denizin yazarı.", "longBio": "Çehov tarzı hikayeciliğinin Türk edebiyatındaki en büyük temsilcisidir. Gözlemci ve şiirsel diliyle balıkçıların, Adalar'ın ve yoksulların sesini öyküye taşımıştır.", "quote": "Bir insanı sevmekle başlayacak her şey.", "image": "images/sait-faik-abasiyanik.jpg" },
    { "id": 15, "name": "Attilâ İlhan", "category": "turk", "isPoet": true, "years": "1925-2005", "movement": "Maviciler", "shortBio": "Romantik devrimciliğin, aşkın ve sinematografik şiirin ustası.", "longBio": "Maviciler akımının öncüsüdür. Büyük şehirlerin ara sokaklarını, gerilimli aşkları, siyasi kaçakları sinematografik bir kurguyla anlatır.", "quote": "Ben sana mecburum bilemezsin.", "image": "images/attila-ilhan.jpg" },
    { "id": 16, "name": "Yaşar Kemal", "category": "turk", "isPoet": false, "years": "1923-2015", "movement": "Toplumcu Gerçekçi", "shortBio": "Anadolu destanlarının ve Çukurova'nın evrensel yazarı.", "longBio": "Türkçenin en zengin sözcük dağarcığına sahip, Nobel'e aday gösterilen ilk yazarımızdır. İnsanın doğayla ve ezenlerle mücadelesini destanlaştırmıştır.", "quote": "İnsan, yüreği kadar yer kaplar.", "image": "images/yasar-kemal.jpg" },
    { "id": 17, "name": "Reşat Nuri Güntekin", "category": "turk", "isPoet": false, "years": "1889-1956", "movement": "Milli Edebiyat", "shortBio": "Anadolu'yu aydınlatan öğretmenlerin ve idealizmin romancısı.", "longBio": "Anadolu'nun sosyal yaşantısını, inançlarını ve yanlış batılılaşmayı müthiş bir gözlem yeteneğiyle ve sade bir Türkçeyle yazmıştır.", "quote": "İnsan bir şeyi çok ciddi olarak arzu etmeye görsün...", "image": "images/resat-nuri-guntekin.jpg" },
    // YENİ EKLENEN YAZARLAR VE ŞAİRLER
    { "id": 18, "name": "Mevlâna Celâleddîn-i Rûmî", "category": "turk", "isPoet": true, "years": "1207-1273", "movement": "Tasavvuf", "shortBio": "İlahi aşkın, hoşgörünün ve evrensel tasavvufun en büyük düşünürü.", "longBio": "Horasan'ın Belh şehrinde doğmuş, Konya'da yaşamıştır. İnsan sevgisi, ilahi aşk ve hoşgörü temeline dayanan felsefesiyle sadece İslam dünyasını değil, tüm insanlığı etkilemiştir. 'Mesnevi' adlı eseri, tasavvuf edebiyatının zirvesi kabul edilir.", "quote": "Gel, gel, ne olursan ol yine gel...", "image": "images/mevlana.jpg" },
    { "id": 19, "name": "Yunus Emre", "category": "turk", "isPoet": true, "years": "1238-1320", "movement": "Tekke ve Tasavvuf", "shortBio": "Halk dilini tasavvufla harmanlayan sevgi ve irfan şairi.", "longBio": "Anadolu Selçuklu Devleti'nin son yılları ile Osmanlı'nın kuruluş döneminde yaşamıştır. Tasavvuf felsefesini, karmaşık terimlerden arındırarak son derece sade ve vurucu bir Türkçe ile halka aktarmıştır. Anadolu hümanizminin kurucusudur.", "quote": "Sevelim sevilelim, bu dünya kimseye kalmaz.", "image": "images/yunus-emre.jpg" },
    { "id": 20, "name": "Ahmet Erhan", "category": "turk", "isPoet": true, "years": "1958-2013", "movement": "80 Kuşağı / Toplumcu", "shortBio": "78 kuşağının acılarını, yalnızlığı ve ölümü ironiyle anlatan şair.", "longBio": "Genç yaşında 'Alacakaranlıktaki Ülke' ile büyük ses getirmiş, Türk şiirine Akdeniz lirizmi ile karanlık bir melankoliyi aynı potada eriterek sunmuştur. Yaşadığı dönemin siyasi buhranlarını bireysel acılarla ustaca harmanlamıştır.", "quote": "Anne ben geldim, üstüm başım uzak yollarla kirli...", "image": "images/ahmet-erhan.jpg" }
];