const localQuotesData = [
    { "id": 1, "authorName": "Sabahattin Ali", "text": "Dünyada hayatın bir tek manası varsa o da sevmektir.", "book": "Kürk Mantolu Madonna" },
    { "id": 2, "authorName": "Sabahattin Ali", "text": "İçimde yarım kalmış bir konuşmanın üzüntüsü vardı.", "book": "Kürk Mantolu Madonna" },
    { "id": 3, "authorName": "Fyodor Dostoyevski", "text": "Her insan, herkesin önünde, her şeyden sorumludur.", "book": "Karamazov Kardeşler" },
    { "id": 4, "authorName": "Oğuz Atay", "text": "Kelimeler albayım, bazı anlamlara gelmiyor.", "book": "Tehlikeli Oyunlar" },
    { "id": 5, "authorName": "Franz Kafka", "text": "Bir kitap, içimizdeki donmuş denize inen bir balta gibi olmalıdır.", "book": "Aforizmalar" },
    { "id": 6, "authorName": "Nazım Hikmet Ran", "text": "Yaşamak şakaya gelmez, büyük bir ciddiyetle yaşayacaksın.", "book": "Yaşamaya Dair" },
    { "id": 7, "authorName": "Cemal Süreya", "text": "Hayat kısa, kuşlar uçuyor.", "book": "Sevda Sözleri" },
    { "id": 8, "authorName": "Ahmet Hamdi Tanpınar", "text": "Ne içindeyim zamanın, ne de büsbütün dışında...", "book": "Bütün Şiirleri" },
    { "id": 9, "authorName": "Virginia Woolf", "text": "Para kazanın, kendinize ait ayrı bir oda yaratın. Ve yazın.", "book": "Kendine Ait Bir Oda" },
    { "id": 10, "authorName": "Gabriel García Márquez", "text": "Hayat, insanın yaşadığı değil; hatırladığıdır.", "book": "Anlatmak İçin Yaşamak" },
    { "id": 11, "authorName": "Sait Faik Abasıyanık", "text": "Bir insanı sevmekle başlayacak her şey.", "book": "Alemdağ'da Var Bir Yılan" },
    { "id": 12, "authorName": "Özdemir Asaf", "text": "Yalnızlık paylaşılmaz, paylaşılsa yalnızlık olmaz.", "book": "Çiçek Senfonisi" },
    { "id": 13, "authorName": "Attilâ İlhan", "text": "Ayrılık sevdaya dahil, çünkü ayrılanlar hala sevgili.", "book": "Ayrılık Sevdaya Dahil" },
    { "id": 14, "authorName": "Yaşar Kemal", "text": "O iyi insanlar, o güzel atlara bindiler çekip gittiler.", "book": "Demirciler Çarşısı Cinayeti" },
    { "id": 15, "authorName": "Mevlâna Celâleddîn-i Rûmî", "text": "Kusur bulmak için bakma birine, bulmak için bakarsan bulursun. Kusuru örtmeyi marifet edin kendine. İşte o zaman kusursuz olursun.", "book": "Mesnevi" },
    { "id": 16, "authorName": "Mevlâna Celâleddîn-i Rûmî", "text": "Mum olmak kolay değildir. Işık saçmak için önce yanmak gerekir.", "book": "Divan-ı Kebir" },
    { "id": 17, "authorName": "Yunus Emre", "text": "İlim ilim bilmektir, ilim kendin bilmektir. Sen kendini bilmezsen, ya nice okumaktır.", "book": "Yunus Emre Divanı" },
    { "id": 18, "authorName": "Yunus Emre", "text": "Sevelim sevilelim, bu dünya kimseye kalmaz.", "book": "Şiirler" },
    { "id": 19, "authorName": "Ahmet Erhan", "text": "Anne ben geldim, üstüm başım uzak yollarla kirli... Temiz ellerinle okşa beni.", "book": "Alacakaranlıktaki Ülke" },
    { "id": 20, "authorName": "Ahmet Erhan", "text": "Bir denizin anası olmaktan yorulmuş, kendi içine akıp duran bir nehir gibiyim.", "book": "Burada Gökyüzü Altında" },
    { "id": 21, "authorName": "Albert Camus", "text": "Kışın en şiddetli anında, içimde sönmek bilmeyen bir yaz olduğunu anladım.", "book": "Denemeler" },
    { "id": 22, "authorName": "Turgut Uyar", "text": "Eylül toparlandı gitti işte, ekim filan da gider bu gidişle.", "book": "Göğe Bakma Durağı" },
    { "id": 23, "authorName": "Oscar Wilde", "text": "Kendin ol, çünkü diğer herkes çoktan kapıldı.", "book": "Önemsiz Bir Kadın" },
    { "id": 24, "authorName": "Stefan Zweig", "text": "Bize hiçbir şey yardımcı olamazdı, ancak kendi kendimize yardım edebilirdik.", "book": "Satranç" },
    { "id": 25, "authorName": "Edip Cansever", "text": "Gökyüzü gibi bir şey bu çocukluk, hiçbir yere gitmiyor.", "book": "Sonrası Kalır" },
    { "id": 26, "authorName": "Antoine de Saint-Exupéry", "text": "İnsan ancak yüreğiyle baktığı zaman doğruyu görebilir. Gerçeğin mayası gözle görülmez.", "book": "Küçük Prens" },
    { "id": 27, "authorName": "Oğuz Atay", "text": "Ben buradayım sevgili okurum, sen neredesin?", "book": "Tutunamayanlar" },
    { "id": 28, "authorName": "Didem Madak", "text": "Çiçekli şiirler yazmama imkan yok artık. Kalbim bir enkaz bu şehirde.", "book": "Grapon Kağıtları" },
    { "id": 29, "authorName": "Lev Tolstoy", "text": "Tüm muhteşem hikayeler iki şekilde başlar: Ya bir insan bir yolculuğa çıkar, ya da şehre bir yabancı gelir.", "book": "İnsan Ne İle Yaşar" },
    { "id": 30, "authorName": "Jose Saramago", "text": "Bakabiliyorsan gör, görebiliyorsan fark et.", "book": "Körlük" },
    { "id": 31, "authorName": "George Orwell", "text": "Özgürlük, insanlara duymak istemedikleri şeyleri söyleme hakkıdır.", "book": "1984" },
    { "id": 32, "authorName": "Victor Hugo", "text": "Ölmek bir şey değil, yaşamamak korkunç.", "book": "Sefiller" },
    { "id": 33, "authorName": "Charles Bukowski", "text": "Yalnızlık üzerine o kadar çok şey biliyorum ki, bu beni korkutuyor.", "book": "Ekmek Arası" },
    { "id": 34, "authorName": "William Shakespeare", "text": "Olmak ya da olmamak, işte bütün mesele bu.", "book": "Hamlet" },
    { "id": 35, "authorName": "Milan Kundera", "text": "Aşkın başladığı yer, hafızanın bittiği yerdir.", "book": "Varolmanın Dayanılmaz Hafifliği" },
    { "id": 36, "authorName": "Umberto Eco", "text": "Kitaplar her zaman başka kitaplardan bahseder ve her hikaye çoktan anlatılmış bir hikayeyi anlatır.", "book": "Gülün Adı" },
    { "id": 37, "authorName": "Nilgün Marmara", "text": "Hayatın neresinden dönülse kârdır.", "book": "Daktiloya Çekilmiş Şiirler" },
    { "id": 38, "authorName": "Orhan Veli Kanık", "text": "Gün olur, alır başımı giderim, denizden yeni çıkmış ağların kokusunda.", "book": "Bütün Şiirleri" },
    { "id": 39, "authorName": "Zülfü Livaneli", "text": "Merhamet zulmün merhemi olamaz.", "book": "Serenad" },
    { "id": 40, "authorName": "Hasan Ali Toptaş", "text": "İnsan dediğin, unutulunca ölür.", "book": "Kuşlar Yasına Gider" },
    { "id": 41, "authorName": "İhsan Oktay Anar", "text": "Dünya bir düştür. Evet, dünya bir rüyadır.", "book": "Puslu Kıtalar Atlası" },
    { "id": 42, "authorName": "Murathan Mungan", "text": "Aşkın ömrü varsa, ayrılığın da bir onuru olmalı.", "book": "Yalnız Bir Opera" },
    { "id": 43, "authorName": "Ece Temelkuran", "text": "Bütün iyiler biraz kırgındır.", "book": "Bütün Kadınların Kafası Karışıktır" },
    { "id": 44, "authorName": "Elif Şafak", "text": "Aşk bir yolculuktur. Bu yolculuğa çıkan her yolcu, istese de istemese de tepeden tırnağa değişir.", "book": "Aşk" },
    { "id": 45, "authorName": "Behçet Necatigil", "text": "Bekleyen her şey bir gün solar ya da ölür.", "book": "Eski Toprak" },
    { "id": 46, "authorName": "Tezer Özlü", "text": "Burası bizim değil, bizi öldürmek isteyenlerin ülkesi.", "book": "Çocukluğun Soğuk Geceleri" },
    { "id": 47, "authorName": "Yusuf Atılgan", "text": "Dünyada her şeyin bir sonu vardı, hatta yalnızlığın bile.", "book": "Anayurt Oteli" },
    { "id": 48, "authorName": "Ernest Hemingway", "text": "İnsan yenilmek için yaratılmadı. Mahvolabilir ama yenilmez.", "book": "Yaşlı Adam ve Deniz" },
    { "id": 49, "authorName": "Friedrich Nietzsche", "text": "Müziksiz bir hayat hata olurdu.", "book": "Putların Alacakaranlığı" },
    { "id": 50, "authorName": "Mark Twain", "text": "Gerçek, ayakkabılarını giymeden yalan dünyayı üç kez dolaşır.", "book": "Otobiyografi" },
    { "id": 51, "authorName": "Peyami Safa", "text": "Biz kimiz? Kendimizi tanımıyoruz.", "book": "Dokuzuncu Hariciye Koğuşu" },
    { "id": 52, "authorName": "Tarık Buğra", "text": "İnsan, insanın kurdu değil, umududur.", "book": "Küçük Ağa" },
    { "id": 53, "authorName": "Halide Edib Adıvar", "text": "Aşk, insanın içindeki en büyük kuvvettir.", "book": "Sinekli Bakkal" },
    { "id": 54, "authorName": "Refik Halid Karay", "text": "Gurbet, insanın içinde büyüyen bir boşluktur.", "book": "Gurbet Hikayeleri" },
    { "id": 55, "authorName": "Necip Fazıl Kısakürek", "text": "Tam otuz yıl saatim işlemiş, ben durmuşum; gökyüzünden habersiz uçurtma uçurmuşum.", "book": "Çile" },
    { "id": 56, "authorName": "Ahmet Arif", "text": "Terk etmedi sevdan beni, aç kaldım, susuz kaldım.", "book": "Hasretinden Prangalar Eskittim" },
    { "id": 57, "authorName": "Cahit Zarifoğlu", "text": "Burası dünya, ne çok kıymet verdik.", "book": "Yedi Güzel Adam" },
    { "id": 58, "authorName": "Sezai Karakoç", "text": "Uzatma dünya sürgünümü benim.", "book": "Monna Rosa" },
    { "id": 59, "authorName": "Cahit Sıtkı Tarancı", "text": "Yaş otuz beş! Yolun yarısı eder.", "book": "Otuz Beş Yaş" },
    { "id": 60, "authorName": "Metin Altıok", "text": "Ömrümce kendimi aradım, durdum.", "book": "Bir Acıya Kiracı" },
    { "id": 61, "authorName": "Sylvia Plath", "text": "Kendi içimde bir cehennem yarattım.", "book": "Sırça Fanus" },
    { "id": 62, "authorName": "Haruki Murakami", "text": "Acı kaçınılmazdır, ama ıstırap çekmek isteğe bağlıdır.", "book": "Koşmasaydım Yazamazdım" },
    { "id": 63, "authorName": "Jorge Luis Borges", "text": "Cennetin bir kütüphane olacağını hayal ettim.", "book": "Yolları Çatallanan Bahçe" },
    { "id": 64, "authorName": "Emily Dickinson", "text": "Umut, ruhun üzerine tünemiş tüylü bir şeydir.", "book": "Şiirler" },
    { "id": 65, "authorName": "J.R.R. Tolkien", "text": "Gezgin olan her insan kaybolmuş değildir.", "book": "Yüzüklerin Efendisi" },
    { "id": 66, "authorName": "Paulo Coelho", "text": "Bir şeyi gerçekten istersen, bütün evren onu gerçekleştirmen için iş birliği yapar.", "book": "Simyacı" },
    { "id": 67, "authorName": "Albert Einstein", "text": "Hayal gücü bilgiden daha önemlidir.", "book": "Fikirler ve Görüşler" },
    { "id": 68, "authorName": "Dante Alighieri", "text": "Yolun ortasında kendimi karanlık bir ormanda buldum.", "book": "İlahi Komedya" },
    { "id": 69, "authorName": "Hermann Hesse", "text": "Kendi içime giden yolu bulmaya çalışıyorum.", "book": "Demian" },
    { "id": 70, "authorName": "Marcel Proust", "text": "Asıl keşif yolculuğu, yeni yerler aramak değil, yeni gözlerle bakmaktır.", "book": "Kayıp Zamanın İzinde" },
    { "id": 71, "authorName": "Jane Austen", "text": "İyi bir insanın her zaman mutlu olacağını kim söylemiş?", "book": "Gurur ve Önyargı" },
    { "id": 72, "authorName": "Charlotte Bronte", "text": "Ben bir kuş değilim ve hiçbir ağ beni hapsedemez.", "book": "Jane Eyre" },
    { "id": 73, "authorName": "Charles Dickens", "text": "Zamanların en iyisiydi, zamanların en kötüsüydü.", "book": "İki Şehrin Hikayesi" },
    { "id": 74, "authorName": "F. Scott Fitzgerald", "text": "Ve böylece, teknelerimizle akıntıya karşı ilerleyip duruyoruz.", "book": "Muhteşem Gatsby" },
    { "id": 75, "authorName": "Khaled Hosseini", "text": "Senin için bin tane olsa yine yakalarım.", "book": "Uçurtma Avcısı" },
    { "id": 76, "authorName": "Ray Bradbury", "text": "Kitapları yakmaktan daha büyük bir suç varsa, o da onları okumamaktır.", "book": "Fahrenheit 451" },
    { "id": 77, "authorName": "Aldous Huxley", "text": "Mutluluk, her zaman bir seçimdir.", "book": "Cesur Yeni Dünya" },
    { "id": 78, "authorName": "Jack London", "text": "Yaşamın amacı sadece hayatta kalmak değil, parlamaktır.", "book": "Beyaz Diş" },
    { "id": 79, "authorName": "Edgar Allan Poe", "text": "Gördüğümüz her şey, bir rüya içinde rüyadır.", "book": "Kuzgun" },
    { "id": 80, "authorName": "Jean-Paul Sartre", "text": "Cehennem, diğer insanlardır.", "book": "Gizli Oturum" },
    { "id": 81, "authorName": "Simone de Beauvoir", "text": "Kadın doğulmaz, kadın olunur.", "book": "İkinci Cinsiyet" },
    { "id": 82, "authorName": "Mihail Bulgakov", "text": "Yazmalar yanmaz.", "book": "Usta ile Margarita" },
    { "id": 83, "authorName": "İvan Turgenyev", "text": "Aşk, ölümden daha güçlüdür.", "book": "Babalar ve Oğullar" },
    { "id": 84, "authorName": "Fyodor Dostoyevski", "text": "Hepimiz Gogol'ün Palto'sundan çıktık.", "book": "Gogol ve Palto Üzerine" },
    { "id": 85, "authorName": "Anton Çehov", "text": "Eğer ilk sahnede duvarda bir tüfek asılıysa, o tüfek patlamalıdır.", "book": "Martı" },
    { "id": 86, "authorName": "Honore de Balzac", "text": "Maddi ihtiyaçlar her zaman manevi duyguların önündedir.", "book": "Vadideki Zambak" },
    { "id": 87, "authorName": "Gustave Flaubert", "text": "Madame Bovary benim!", "book": "Madame Bovary" },
    { "id": 88, "authorName": "Stendhal", "text": "Roman, yol boyunca gezdirilen bir aynadır.", "book": "Kırmızı ve Siyah" },
    { "id": 89, "authorName": "Yakup Kadri Karaosmanoğlu", "text": "Anadolu bir ıstırap denizidir.", "book": "Yaban" },
    { "id": 90, "authorName": "Reşat Nuri Güntekin", "text": "Gönül, sevdiğinden asla vazgeçmez.", "book": "Çalıkuşu" },
    { "id": 91, "authorName": "Orhan Pamuk", "text": "Bir gün bir kitap okudum ve bütün hayatım değişti.", "book": "Yeni Hayat" },
    { "id": 92, "authorName": "Ayşe Kulin", "text": "Hayat akar gider, biz sadece izleriz.", "book": "Adı: Aylin" },
    { "id": 93, "authorName": "Buket Uzuner", "text": "Her insan bir adadır.", "book": "Kumral Ada Mavi Tuna" },
    { "id": 94, "authorName": "Leyla Erbil", "text": "Aşk, bir başkaldırıdır.", "book": "Tuhaf Bir Kadın" },
    { "id": 95, "authorName": "Latife Tekin", "text": "Kelimeler yaralarımızı örter.", "book": "Sevgili Arsız Ölüm" },
    { "id": 96, "authorName": "Ahmet Ümit", "text": "Aşk, imkansız olanı istemektir.", "book": "İstanbul Hatırası" },
    { "id": 97, "authorName": "Sunay Akın", "text": "Şiir, hayatın en saf halidir.", "book": "Kız Kulesi'ndeki Kızılderili" },
    { "id": 98, "authorName": "Ataol Behramoğlu", "text": "Yaşadıklarımdan öğrendiğim bir şey var.", "book": "Yaşadıklarımdan Öğrendiğim Bir Şey Var" },
    { "id": 99, "authorName": "Can Yücel", "text": "En uzak mesafe ne Afrika'dır ne Çin... İki kafa arasındaki mesafedir.", "book": "Sevgi Duvarı" },
    { "id": 100, "authorName": "Şükrü Erbaş", "text": "Ömür dediğimiz nedir ki? Çay buz olana kadar geçen zaman.", "book": "Bağbozumu Şarkıları" },
    { "id": 101, "authorName": "Tezer Özlü", "text": "Neden yazılır? Dünya acılı olduğu için yazılır. Duygular taştığı için yazılır. İnsanın kendi zavallılığından sıyrılması için yazılır.", "book": "Yaşamın Ucuna Yolculuk" },
    { "id": 102, "authorName": "Tezer Özlü", "text": "En büyük acı, başkalarının acısını anlayamamaktır.", "book": "Çocukluğun Soğuk Geceleri" },
    { "id": 103, "authorName": "Nilgün Marmara", "text": "Çocukluğun kendini saf bir biçimde akışa bırakması ne güzeldi.", "book": "Daktiloya Çekilmiş Şiirler" },
    { "id": 104, "authorName": "Nilgün Marmara", "text": "Ey, iki adımlık yerküre... Senin bütün arka bahçelerini gördüm ben!", "book": "Metinler" },
    { "id": 105, "authorName": "Orhan Kemal", "text": "İnsanlığın en büyük keşfi ateşi veya tekerleği bulması değil, empati kurabilmesidir.", "book": "Murtaza" },
    { "id": 106, "authorName": "Orhan Kemal", "text": "Ekmek peşinde koşarken, şerefini arkada bırakmamak lazımdır.", "book": "Bereketli Topraklar Üzerinde" },
    { "id": 107, "authorName": "Yahya Kemal Beyatlı", "text": "İnsan alemde hayal ettiği müddetçe yaşar.", "book": "Kendi Gök Kubbemiz" },
    { "id": 108, "authorName": "Cahit Sıtkı Tarancı", "text": "Memleket isterim, ne zengin fakir ne sen ben farkı olsun. Kış günü herkesin evi barkı olsun.", "book": "Otuz Beş Yaş" },
    { "id": 109, "authorName": "Necip Fazıl Kısakürek", "text": "Tomurcuk derdinde olmayan ağaç, odundur.", "book": "Çile" },
    { "id": 110, "authorName": "Necip Fazıl Kısakürek", "text": "Ayağın taşa takıldığında 'Allah kahretsin' bile deme, 'Dua et ki taşa takılan bir ayağın var' de.", "book": "Cinnet Mustatili" },
    { "id": 111, "authorName": "İhsan Oktay Anar", "text": "Hiç kimse, diğerinin hissettiği acıyı tam olarak hissedemez. Çekilen acı, çekenin kendisine aittir.", "book": "Puslu Kıtalar Atlası" },
    { "id": 112, "authorName": "İhsan Oktay Anar", "text": "Bilmek yanmaya mahkum olmaktır. Çünkü gerçeğin ateşi, yalanın serinliğinden daima daha yakıcıdır.", "book": "Amat" },
    { "id": 113, "authorName": "Edgar Allan Poe", "text": "Gerçekten delirdim mi, yoksa delilik en yüksek zeka seviyesi midir, hala çözebilmiş değilim.", "book": "Seçme Öyküler" },
    { "id": 114, "authorName": "Victor Hugo", "text": "Geceyi sevmeyen, gündüzün kıymetini ne bilsin.", "book": "Sefiller" },
    { "id": 115, "authorName": "Victor Hugo", "text": "Bir çocuğu eğitmeye karar verdiğinizde işe büyükannesinden başlayın.", "book": "Sefiller" },
    { "id": 116, "authorName": "Sylvia Plath", "text": "Gülümsememi yüzüme bir maske gibi takıyorum, altındaki boşluğu kimse görmesin diye.", "book": "Sırça Fanus" },
    { "id": 117, "authorName": "Sylvia Plath", "text": "Bir kadın ne kadar güçlü durursa dursun, içindeki o küçük kız çocuğu daima bir yerlerde ağlar.", "book": "Günlükler" },
    { "id": 118, "authorName": "Haruki Murakami", "text": "Eğer herkesin okuduğu kitapları okursan, sadece herkesin düşündüğü şeyleri düşünebilirsin.", "book": "İmkansızın Şarkısı" },
    { "id": 119, "authorName": "Haruki Murakami", "text": "Birini unutmak istiyorsan, onun hakkında düşünmeyi bırakmalısın. Onu unutmaya çalışmak da onu düşünmektir.", "book": "Sahilde Kafka" },
    { "id": 120, "authorName": "Charles Bukowski", "text": "İnsanları tanıdıkça, hayvanları daha çok seviyorum.", "book": "Kapalı Gişe" },
    { "id": 121, "authorName": "Charles Bukowski", "text": "Beni anlamıyorlardı. Ben de onlara kendimi anlatmaya çalışmaktan çoktan vazgeçmiştim.", "book": "Ekmek Arası" }
];